language: node_js
node_js:
- '6'

before_install:
  - stty cols 80

env:
  global:
    secure: orU+oZpgaGeR1IDirCe87msd2HemNCLS+8WgcHccPxLZcc81ZACoTAUg3kA+en0xrJQ6Dm/GP3OOv2Xj30dl7ufzm6dcr0ivgkcq+p0eq38qiO0ZKlW6GwcAU1hfirU7HfRbWipIDyclzDOV5LdLFZ1C6/9BmoBb/Dbjb4dlXURW3SJ+Wl/wFqcIRpZ8gHnXDt80uBF3i+fXi4sh3QRtbUE4iIPlMVPJiOvW6poS2OF0U5fJ9DawE9fIC6jmFzfXSyaU5PLdoZWYuPnlSKQsuOGL419RW8DcmDJnf86i90BCVg1L5lIzNmPS1xYFaJoZbMY1fFeUFJ+i/nlZ+nTRW7G638C4BU7NCtgo5PzN6KbTSimLLe+0xpBRiejGllYcoARRn3PKKeyll29o65PQC690IR8hXchY725kik24RAKkfWRLhfcoV01q7NsweUW8zFvwjmZsXPvvdEDAVTYwJVw1aREMetiCzgsWFDzwEUT5D9f7I83+rfpKEzoVqgCeGUbnl2sbplwIg70pGSKq+gLHxppe5M/tLHQs37JLWML6AXt7YAXy32sNGQF4cMGF7z1Aj6Svfq3rOeZdWADl+HvQYi2GY+BbQiTpeBqobybYLcnonKccgqN4L8WAWKX35jqTcgbQx5wablkQFerzK1thg9/DkNZXHpnERr4QwrY=
dist: trusty
sudo: required
addons:
  firefox: stable
  chrome: stable

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3
- npm install -g concurrently@3.1.0
script:
- npm run build_knockout_dev
- npm run build_knockout_prod
- npm run build_react_dev
- npm run build_react_prod
- npm run build_angular_dev
- npm run build_angular_prod
- npm run build_jquery_dev
- npm run build_jquery_prod
- npm run build_vue_dev
- npm run build_vue_prod
- karma start --single-run
- http-server --silent &
- testcafe chrome testCafe/ --reporter minimal
#- npm run testcafe_sauce
- if [[ "$TRAVIS_EVENT_TYPE" = "cron" ]]; then echo "Starting functional tests on SauceLabs..."; npm run testcafe_sauce; fi
before_deploy: tar -zcvf surveyjs.tar.gz packages
deploy:
- provider: releases
  api_key:
    secure: HScEzS1LzcJ9DSe5q7VZJbBrEYfrDBYjBz2AZ6qjuBOS157IazXNNz96fZHoKIovNWP4qWFN0D21cyJU9TGW3YKlnhiteC6dUVFhRPscmoLnjIvsEU0QlM2cWzt2uVkw+Jv/wjDqL3ClCKqUh0pm+6TIqgfYhGYldV/l7Ls1mXTqxzdYLcj3iL1Moryuk843NoeVBlbBB5r00rpImBkt88aFgecwuWtRLlq9AmJ0TF+QWOd/VPAq0NkPaLnkNSovElsZ2+ekR0l93N/onamxZg7oWOHlKlnyGumA7nwvP1UjhyvUlnF9wN71tKvoYcurc+5GW5esMaBAMRUt+o0mIaSq77NGnM/4Htwfbg+/j4rJrkgQwo7RGLgRbL+ln0N+YRfF3haIo5iRhu6tRCEFSNIvsLn1mXCxbFMbCQCJNo4XO11SbSrmHJBuAd3V3vpSA8CYQGSTnwSgagA0bHY9Nr4Vfk+qai1FboPj1uujOMrctXfJX6cH5u278wnoGmZUrSWXKbjjI6h72r6mMnIdSdlMkzXjgfVLzrQS507zt84gNguo4IFlLULROPI329HOppb1G1cyYRZ2wgjtOmwKYAasEwoBtEcOXQf305WQmAsnyIBS8XQvFMTiNR7fGGwnd78kC4pqEh1zRNvzUvJMJqvBa9U5SdHNwSpFb2Gn+KI=
  file:
  - surveyjs.tar.gz
  skip_cleanup: true
  on:
    tags: true
- provider: script
  script: chmod +x ./deploy_npm.sh && ./deploy_npm.sh
  skip_cleanup: true
  on:
    tags: true
notifications:
  email:
    recipients:
      - andrew.telnov@gmail.com
