language: node_js
node_js:
- '8'

before_install:
  - stty cols 80

env:
  global:
  - secure: L5vNGeb6J1ny0hZ4GX5DzC4usAswY6tm6mNHURiry1O+mHA5J44I6ORjere7fumK+DMnP/7SM5TjZ54kyjgP5sfp1U713atCxjhxL4rxgCDQy9mPQkrVohubmpuzlkTGjW1N/dWLUk3+HLSo+ze++DBpwryqxQxTenlkMAtVBDuTMbaLzJ+Nr2TLaqTLp053q9vBmM0c/VFL5kfFwUO/+pbVsScVL3c0B/KKPs0OMJKyjYRSH/m+5DBgB81meAZeSzS7vcvM8W1yKv1zTBW8fUQTh4+jWAIXWz8COSoeuPSA8yHax0UJ7CkqdlzZ8qT1+hKIIuiSSnlYGtET9/UUJPVeONk2sAHayfVqBqkQiD0m/cksaiiUYUUJf/4kcLjKMJWMAnbjRpUlhQFa+KJPbDVOVWyRrVmVpkrobGAmlU9gc1Ca+ceJ1ynLncixomYuZHcIV+RDX2eqZRxPw+FvcSAx5umzVAjHrKEEqa1m06V0aUWIozhXPIsUbWyc4Kx/tJ+qAMmOo8cohgmH+HWefeKxyVvwuiyI5xZZUigX0wMYFLim4bZS1s9C0ifhdBmKgJgcv0ZB0C+8IYavoMyfmnoMuDRpuTpoi7EDlcfhvs5Ec+VFUzMz2asA3aSDDsNnOun0RivWPG4uNCmYfrzCji4t4dYv0MIILBj9l7n9X2g=
  - secure: hHN5UosmuwIX3WWJR0ap7u5cmlFzr1ERaLJPlQ27n1FORMargBsvPA0GRTbesYM3dGfjK5rOob+71yE/sfCJsGusMW0KqHYy2pwVag/8cJJ6ndpV+bvLwdKRuc7sVN+s/eryLrstEJfoGrVm955Nvuf/XuGWCKCFRP9QXoIS8Y4GuDilPXorj/p4owfrifAss70vjyJxC/mjwKBWHRpkSfQUjdywXQCjRyv79B3tlNr+i9hZirhmWlJHlrXUXeK33W2rPSRjWM90CczVGr6Sh8caQj5yy/n3vvWISWkNgZs6o60qLJmYylTEjrcdMVWaznmK4O9UpF4H/Bh6pJiEMGiKa+Ylrv4s9/Syy+cwQRnRicD/uDLdGi8cB5v8iiHJXmH9GsHugvxv7QWUzoqrfxal1Iw6H6K3GHIyv+jY2K2ebLzAGX3A7uoNdCHjsqjLC4OGxwgEWuT65G4a0PEZlRv7IYzbIEPTM5kl2dHn2q8z8e0VwPpTGKuWD6KwlZ0HmlVR0IFQ2vPh1nyJVZJyZ7cJTHqCMeKLL/OKLONeGM5qUz1csoN5Riy8P+7/LYelaV88Tu2Ie4pimncwbKRIhF+QcoXSy5qfU/7E+CWy7z5fYrotldljJNwSns05cESr+1s/tekmgP0sDBMbQRCHhsRSVVG81nLdAZc8d+26dnA=
  - secure: m0p82j4sBXaRB1auAe5Qu7VKawjfcgiPUuQs7R9CUgbHPI8k9kxUb9ICmnO2/oxtI6hKj0sZj2J5o2hCoR85Dx3U7jxR8taW6qkW0mi532UIzSq4zFZWXJjtUkvBNhkdUbyABzLaiiLfkDMOi7bMa0vIQ/sBSa4hWbs0fkqYHW48f7r0yJVkSYPK/QInXUzDsaYyPOQh/feThbqO8nIthyn7LAO8lrxBd8zS4i+LMD0Rp1OQAjjbk/cD6R4qq8bcWjiK7MVpwYy1E5BG4fqggFl/I+AUkwXrnBJsA4GI00dBVS1Z8XCfbyi2BeMs70gIYrYB+zFw/R/sKBHJGxk2C3Fu6ehTHC+CucI21s6OzmvhdaJF4f5KTL1rioqvb0GAXl1tPK8YcJYxo+zqCxlo74lGhsvjxEDnyVtdtMoUQTIw2nqb9r3265SZXi1yRGzwculLWnnKrH8x3skOq2MnMIBGURibUgMywxR02QNFbXk5fjWjZtB6c8niKrdjPmz8AjNoi5gNQG8bCJC/hAU6faIIfdig6TKZwlQdCPQGxR/fr/WemAvoXjHQTkbJImlJ7qa2Ayos2wB+J3AUAvGwVQmKLdngEKtyGkJyrph99nClOCm0hl8BhBqX0sPQH2EH/c/As0ycxkKTov7+j3jbvanSFSAuE25g1pyJ3dhoCpw=
dist: trusty
sudo: required
addons:
  firefox: stable
  chrome: stable

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3
- npm install -g concurrently@3.1.0
script:
- npm run build_knockout_dev
- npm run build_knockout_prod
- npm run build_react_dev
- npm run build_react_prod
- npm run build_angular_dev
- npm run build_angular_prod
- npm run build_jquery_dev
- npm run build_jquery_prod
- npm run build_vue_dev
- npm run build_vue_prod
- karma start --single-run
- http-server --silent &
- testcafe chrome testCafe/ --reporter minimal
#- npm run testcafe_sauce
- if [[ "$TRAVIS_EVENT_TYPE" = "cron" ]]; then echo "Starting functional tests on SauceLabs..."; npm run testcafe_sauce; fi
before_deploy: 
- tar -zcvf surveyjs.tar.gz packages
- npm run doc_gen
deploy:
- provider: releases
  api_key:
    secure: Lr8z0Dj+oakqyzK+2zQeZGW5QwprPzlXl5ODN7ajk0IRn2aTMceKgs0uk2iqO7AdyqkGrDD89NeRFlKBbiPVrsee4WRV+vf9FinDG6BRtEoHIScQzHeKlvqdSU3QtjUxdQVqwL1oa6VJYrIxdctFcKkZqh76IVzbacK9bzZavDZZQ7offhyBKP/VEPgKuYBPfCJiKI7kW0niWUztBlPbjpo1Tz1KlTTBrIBNpRka2crZ7n0eADXwyl6bA1EKx5Za2YE0pPeKnutKSymDPT147lovb+ViRkKcxT/xRu2xtzb9exsH/BB2KEOgS+llmON57jI00ntnVhDsFRiZQ6nP6sMM1qiRpkO+nu6tH4yRLptw6ekR2had+ERvaNr4SO4gvplo2RtzYufUPjbBLc40aQDu5DBeLmvTgKE4WLL8DiQ0cC7Gf+AfJRah3VtPfoQbCd2n/AkwR8yObrZDdJPwBAbpPCXNONHOK8Exmgz1Q7HDcm5BLMnTfyAjzpbZ23gtilxvtUAqUorwkDiPms3eEjWYNw5cew0hTHlavWaAt/wSKlX2Z42WgUbrCPQRGYIEL6nE9cE07HOhd0swddNS/Jx5u762ldPtOuaTkRUqDrLX0upwXSl47VHmgUAoHi8JUzPW0quUMWywH4gKdqcV5I4kYICvE6PqrXbNotseKIU=
  file:
  - surveyjs.tar.gz
  skip_cleanup: true
  on:
    tags: true
- provider: script
  script: chmod +x ./deploy_npm.sh && ./deploy_npm.sh
  skip_cleanup: true
  on:
    tags: true
- provider: script
  script: npm run doc_update
  skip_cleanup: true
notifications:
  email:
    recipients:
      - andrew.telnov@gmail.com
