# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

resources:
  repositories:
    - repository: Service # The name used to reference this repository in the checkout step
      type: github
      endpoint: dmitrykurmanov:admin
      name: surveyjs/service
    - repository: EmptyRepo
      type: github
      endpoint: dmitrykurmanov:admin
      name: surveyjs/azure-pipelines-repo-dont-remove-please

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm


trigger:
  batch: true
  branches:
    include:
      - master
  tags:
    exclude:
      - v*.*.*

pool:
  vmImage: ubuntu-latest

jobs:

- job: CoreAngularJquery

  steps:
    - checkout: self
    - checkout: EmptyRepo
      persistCredentials: true
      clean: true

    - task: NodeTool@0
      inputs:
        versionSpec: "14.x"
      displayName: "Install Node.js"
  
    - task: Cache@2
      inputs:
        key: 'npm | "$(Agent.OS)" | package.json'
        restoreKeys: |
          npm | "$(Agent.OS)"
        path: $(npm_config_cache)
      displayName: Cache NPM

    # setup next release version
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: "specific"
        project: "af2804d2-859a-4705-9ef5-cdf46d1d5d4f"
        pipeline: "47"
        buildVersionToDownload: "latest"
        downloadType: "single"
        artifactName: "ReleaseVersionFile"
        downloadPath: "$(System.ArtifactsDirectory)"

    - task: CopyFiles@2
      inputs:
        SourceFolder: "$(System.ArtifactsDirectory)/ReleaseVersionFile/"
        Contents: "version.txt"
        TargetFolder: "$(Build.SourcesDirectory)/"
        OverWrite: true
      displayName: "Copy Build Artifact - SurveyJSVersion File"

    - powershell: |
        $version = Get-Content $(Build.SourcesDirectory)/version.txt
        Write-Host "##vso[task.setvariable variable=SurveyJSVersion;]$version"
      displayName: "setup SurveyJSVersion variable from SurveyJSVersionFile"
    ##########################################################################

    - script: |
        cd $(Build.SourcesDirectory)/survey-library
        npm install
        npm run release -- --release-as $(SurveyJSVersion)
        git status
      displayName: "NPM install"

    - script: |
        cd $(Build.SourcesDirectory)/survey-library
        npm run build_core
      displayName: "Build Core"

    - script: |
        cd $(Build.SourcesDirectory)/survey-library
        npm run build_angular
      displayName: "Build Angular"

    - script: |
        cd $(Build.SourcesDirectory)/survey-library
        npm run build_jquery
      displayName: "Build jQuery"

    - task: CopyFiles@2
      inputs:
        SourceFolder: "$(Build.SourcesDirectory)/survey-library/build/survey-core"
        TargetFolder: "$(Build.ArtifactStagingDirectory)/SurveyJSLibraryBuild/packages/survey-core"

    - task: CopyFiles@2
      inputs:
        SourceFolder: "$(Build.SourcesDirectory)/survey-library/build/survey-angular"
        TargetFolder: "$(Build.ArtifactStagingDirectory)/SurveyJSLibraryBuild/packages/survey-angular"

    - task: CopyFiles@2
      inputs:
        SourceFolder: "$(Build.SourcesDirectory)/survey-library/build/survey-jquery"
        TargetFolder: "$(Build.ArtifactStagingDirectory)/SurveyJSLibraryBuild/packages/survey-jquery"

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: "$(Build.ArtifactStagingDirectory)/SurveyJSLibraryBuild/"
        ArtifactName: "SurveyJSLibraryBuildCore"
        publishLocation: "Container"


- job: Knockout
  steps:
    - checkout: self
    - checkout: EmptyRepo
      persistCredentials: true
      clean: true

    - task: NodeTool@0
      inputs:
        versionSpec: "14.x"
      displayName: "Install Node.js"

    - task: Cache@2
      inputs:
        key: 'npm | "$(Agent.OS)" | package.json'
        restoreKeys: |
          npm | "$(Agent.OS)"
        path: $(npm_config_cache)
      displayName: Cache NPM

    # setup next release version
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: "specific"
        project: "af2804d2-859a-4705-9ef5-cdf46d1d5d4f"
        pipeline: "47"
        buildVersionToDownload: "latest"
        downloadType: "single"
        artifactName: "ReleaseVersionFile"
        downloadPath: "$(System.ArtifactsDirectory)"

    - task: CopyFiles@2
      inputs:
        SourceFolder: "$(System.ArtifactsDirectory)/ReleaseVersionFile/"
        Contents: "version.txt"
        TargetFolder: "$(Build.SourcesDirectory)/"
        OverWrite: true
      displayName: "Copy Build Artifact - SurveyJSVersion File"

    - powershell: |
        $version = Get-Content $(Build.SourcesDirectory)/version.txt
        Write-Host "##vso[task.setvariable variable=SurveyJSVersion;]$version"
      displayName: "setup SurveyJSVersion variable from SurveyJSVersionFile"
    ##########################################################################

    - script: |
        cd $(Build.SourcesDirectory)/survey-library
        npm install
        npm run release -- --release-as $(SurveyJSVersion)
        git status
      displayName: "NPM install"

    - script: |
        cd $(Build.SourcesDirectory)/survey-library
        npm run build_knockout
      displayName: "Build Knockout"

    - script: |
        cd $(Build.SourcesDirectory)/survey-library
        npm run build_core
        npm run build_knockout_ui
      displayName: "Build Knockout UI"

    - script: |
        cd $(Build.SourcesDirectory)/survey-library
        npm run testsingle
      displayName: "run unit tests"

    - script: |
        cd $(Build.SourcesDirectory)/survey-library
        npm run testcafe:ko
      displayName: "run functional tests"

    - task: CopyFiles@2
      inputs:
        SourceFolder: "$(Build.SourcesDirectory)/survey-library/build/survey-knockout"
        TargetFolder: "$(Build.ArtifactStagingDirectory)/SurveyJSLibraryBuild/packages/survey-knockout"

    - task: CopyFiles@2
      inputs:
        SourceFolder: "$(Build.SourcesDirectory)/survey-library/build/survey-knockout-ui"
        TargetFolder: "$(Build.ArtifactStagingDirectory)/SurveyJSLibraryBuild/packages/survey-knockout-ui"

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: "$(Build.ArtifactStagingDirectory)/SurveyJSLibraryBuild/"
        ArtifactName: "SurveyJSLibraryBuildKnockout"
        publishLocation: "Container"


- job: React

  steps:
    - checkout: self
    - checkout: EmptyRepo
      persistCredentials: true
      clean: true

    - task: NodeTool@0
      inputs:
        versionSpec: "14.x"
      displayName: "Install Node.js"

    - task: Cache@2
      inputs:
        key: 'npm | "$(Agent.OS)" | package.json'
        restoreKeys: |
          npm | "$(Agent.OS)"
        path: $(npm_config_cache)
      displayName: Cache NPM

    # setup next release version
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: "specific"
        project: "af2804d2-859a-4705-9ef5-cdf46d1d5d4f"
        pipeline: "47"
        buildVersionToDownload: "latest"
        downloadType: "single"
        artifactName: "ReleaseVersionFile"
        downloadPath: "$(System.ArtifactsDirectory)"

    - task: CopyFiles@2
      inputs:
        SourceFolder: "$(System.ArtifactsDirectory)/ReleaseVersionFile/"
        Contents: "version.txt"
        TargetFolder: "$(Build.SourcesDirectory)/"
        OverWrite: true
      displayName: "Copy Build Artifact - SurveyJSVersion File"

    - powershell: |
        $version = Get-Content $(Build.SourcesDirectory)/version.txt
        Write-Host "##vso[task.setvariable variable=SurveyJSVersion;]$version"
      displayName: "setup SurveyJSVersion variable from SurveyJSVersionFile"
    ##########################################################################

    - script: |
        cd $(Build.SourcesDirectory)/survey-library
        npm install
        npm run release -- --release-as $(SurveyJSVersion)
        git status
      displayName: "NPM install"

    - script: |
        cd $(Build.SourcesDirectory)/survey-library
        npm run build_react
      displayName: "Build React"

    - script: |
        cd $(Build.SourcesDirectory)/survey-library
        npm run build_core
        npm run build_react_ui
      displayName: "Build React UI"

    - script: |
        cd $(Build.SourcesDirectory)/survey-library
        npm run testcafe:react
      displayName: "run functional tests"

    - task: CopyFiles@2
      inputs:
        SourceFolder: "$(Build.SourcesDirectory)/survey-library/build/survey-react"
        TargetFolder: "$(Build.ArtifactStagingDirectory)/SurveyJSLibraryBuild/packages/survey-react"

    - task: CopyFiles@2
      inputs:
        SourceFolder: "$(Build.SourcesDirectory)/survey-library/build/survey-react-ui"
        TargetFolder: "$(Build.ArtifactStagingDirectory)/SurveyJSLibraryBuild/packages/survey-react-ui"

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: "$(Build.ArtifactStagingDirectory)/SurveyJSLibraryBuild/"
        ArtifactName: "SurveyJSLibraryBuildReact"
        publishLocation: "Container"


- job: Vue

  steps:
    - checkout: self
    - checkout: EmptyRepo
      persistCredentials: true
      clean: true

    - task: NodeTool@0
      inputs:
        versionSpec: "14.x"
      displayName: "Install Node.js"

    - task: Cache@2
      inputs:
        key: 'npm | "$(Agent.OS)" | package.json'
        restoreKeys: |
          npm | "$(Agent.OS)"
        path: $(npm_config_cache)
      displayName: Cache NPM

    # setup next release version
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: "specific"
        project: "af2804d2-859a-4705-9ef5-cdf46d1d5d4f"
        pipeline: "47"
        buildVersionToDownload: "latest"
        downloadType: "single"
        artifactName: "ReleaseVersionFile"
        downloadPath: "$(System.ArtifactsDirectory)"

    - task: CopyFiles@2
      inputs:
        SourceFolder: "$(System.ArtifactsDirectory)/ReleaseVersionFile/"
        Contents: "version.txt"
        TargetFolder: "$(Build.SourcesDirectory)/"
        OverWrite: true
      displayName: "Copy Build Artifact - SurveyJSVersion File"

    - powershell: |
        $version = Get-Content $(Build.SourcesDirectory)/version.txt
        Write-Host "##vso[task.setvariable variable=SurveyJSVersion;]$version"
      displayName: "setup SurveyJSVersion variable from SurveyJSVersionFile"
    ##########################################################################

    - script: |
        cd $(Build.SourcesDirectory)/survey-library
        npm install
        npm run release -- --release-as $(SurveyJSVersion)
        git status
      displayName: "NPM install"

    - script: |
        cd $(Build.SourcesDirectory)/survey-library
        npm run build_vue
      displayName: "Build Vue"

    - script: |
        cd $(Build.SourcesDirectory)/survey-library
        npm run build_core
        npm run build_vue_ui
      displayName: "Build Vue UI"

    - script: |
        cd $(Build.SourcesDirectory)/survey-library
        npm run testcafe:vue
      displayName: "Vue functional tests"

    - task: CopyFiles@2
      inputs:
        SourceFolder: "$(Build.SourcesDirectory)/survey-library/build/survey-vue"
        TargetFolder: "$(Build.ArtifactStagingDirectory)/SurveyJSLibraryBuild/packages/survey-vue"

    - task: CopyFiles@2
      inputs:
        SourceFolder: "$(Build.SourcesDirectory)/survey-library/build/survey-vue-ui"
        TargetFolder: "$(Build.ArtifactStagingDirectory)/SurveyJSLibraryBuild/packages/survey-vue-ui"

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: "$(Build.ArtifactStagingDirectory)/SurveyJSLibraryBuild/"
        ArtifactName: "SurveyJSLibraryBuildVue"
        publishLocation: "Container"


- job: Finalize
  dependsOn:
    - CoreAngularJquery
    - Knockout
    - React
    - Vue

  steps:
    - checkout: self
    - checkout: Service
      persistCredentials: true
      clean: true

    - task: NodeTool@0
      inputs:
        versionSpec: "14.x"
      displayName: "Install Node.js"

    - task: Cache@2
      inputs:
        key: 'npm | "$(Agent.OS)" | package.json'
        restoreKeys: |
          npm | "$(Agent.OS)"
        path: $(npm_config_cache)
      displayName: Cache NPM

    # setup next release version
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: "specific"
        project: "af2804d2-859a-4705-9ef5-cdf46d1d5d4f"
        pipeline: "47"
        buildVersionToDownload: "latest"
        downloadType: "single"
        artifactName: "ReleaseVersionFile"
        downloadPath: "$(System.ArtifactsDirectory)"

    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'SurveyJSLibraryBuildCore'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: CopyFiles@2
      inputs:
        SourceFolder: "$(System.ArtifactsDirectory)/SurveyJSLibraryBuildCore/packages/survey-core"
        TargetFolder: "$(Build.SourcesDirectory)/survey-library/build/survey-core"

    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'SurveyJSLibraryBuildKnockout'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: CopyFiles@2
      inputs:
        SourceFolder: "$(System.ArtifactsDirectory)/SurveyJSLibraryBuildKnockout/packages/survey-knockout"
        TargetFolder: "$(Build.SourcesDirectory)/survey-library/build/survey-knockout"

    - task: CopyFiles@2
      inputs:
        SourceFolder: "$(System.ArtifactsDirectory)/SurveyJSLibraryBuildKnockout/packages/survey-knockout-ui"
        TargetFolder: "$(Build.SourcesDirectory)/survey-library/build/survey-knockout-ui"

    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'SurveyJSLibraryBuildReact'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: CopyFiles@2
      inputs:
        SourceFolder: "$(System.ArtifactsDirectory)/SurveyJSLibraryBuildReact/packages/survey-react"
        TargetFolder: "$(Build.SourcesDirectory)/survey-library/build/survey-react"

    - task: CopyFiles@2
      inputs:
        SourceFolder: "$(System.ArtifactsDirectory)/SurveyJSLibraryBuildReact/packages/survey-react-ui"
        TargetFolder: "$(Build.SourcesDirectory)/survey-library/build/survey-react-ui"

    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'SurveyJSLibraryBuildVue'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: CopyFiles@2
      inputs:
        SourceFolder: "$(System.ArtifactsDirectory)/SurveyJSLibraryBuildVue/packages/survey-vue"
        TargetFolder: "$(Build.SourcesDirectory)/survey-library/build/survey-vue"

    - task: CopyFiles@2
      inputs:
        SourceFolder: "$(System.ArtifactsDirectory)/SurveyJSLibraryBuildVue/packages/survey-vue-ui"
        TargetFolder: "$(Build.SourcesDirectory)/survey-library/build/survey-vue-ui"

    - task: CopyFiles@2
      inputs:
        SourceFolder: "$(System.ArtifactsDirectory)/SurveyJSLibraryBuildCore/packages/survey-jquery"
        TargetFolder: "$(Build.SourcesDirectory)/survey-library/build/survey-jquery"

    - task: CopyFiles@2
      inputs:
        SourceFolder: "$(System.ArtifactsDirectory)/SurveyJSLibraryBuildCore/packages/survey-angular"
        TargetFolder: "$(Build.SourcesDirectory)/survey-library/build/survey-angular"

    - task: CopyFiles@2
      inputs:
        SourceFolder: "$(System.ArtifactsDirectory)/ReleaseVersionFile/"
        Contents: "version.txt"
        TargetFolder: "$(Build.SourcesDirectory)/"
        OverWrite: true
      displayName: "Copy Build Artifact - SurveyJSVersion File"

    - powershell: |
        $version = Get-Content $(Build.SourcesDirectory)/version.txt
        Write-Host "##vso[task.setvariable variable=SurveyJSVersion;]$version"
      displayName: "setup SurveyJSVersion variable from SurveyJSVersionFile"

    - script: |
        cd $(Build.SourcesDirectory)/survey-library
        npm install
      displayName: "npm install"

    - script: |
        cd $(Build.SourcesDirectory)/survey-library
        npm run doc_gen
      displayName: "generate docs"

    - task: CopyFiles@2
      inputs:
        SourceFolder: "$(Build.SourcesDirectory)/survey-library/docs"
        TargetFolder: "$(Build.SourcesDirectory)/service/surveyjs.io/App_Data/DocsLibrary"
        CleanTargetFolder: true
      displayName: "copy generated docs to the local surveyjs/service repo"

    # read about the problem with git output ($env:GIT_REDIRECT_STDERR = '2>&1') :
    # https://github.com/microsoft/azure-pipelines-yaml/issues/248
    # https://stackoverflow.com/questions/58485585/azure-pipeline-powershell-and-git-on-windows-server-2019-gives-error-in-output
    - powershell: |
        cd $(Build.SourcesDirectory)/service
        $env:GIT_REDIRECT_STDERR = '2>&1'
        git config --global user.email "kurmanov.work@gmail.com"
        git config --global user.name "dmitrykurmanov"
        git checkout master
        git pull origin master
        git fetch --tags --force
        git add surveyjs.io/App_Data/DocsLibrary
        git commit -m "updated survey-library docs"
        git pull origin master
        git push origin master
      displayName: "git surveyjs/service push updated docs"

    - task: CopyFiles@2
      inputs:
        SourceFolder: "$(Build.SourcesDirectory)/survey-library/build"
        TargetFolder: "$(Build.ArtifactStagingDirectory)/SurveyJSLibraryBuild/packages"

    - task: CopyFiles@2
      inputs:
        SourceFolder: "$(Build.SourcesDirectory)/survey-library/build"
        TargetFolder: "$(Build.ArtifactStagingDirectory)/SurveyJSLibraryBuild/build"

    #trigger next build via the artifact file 'version.txt'
    - task: CopyFiles@2
      inputs:
        contents: "version.txt"
        targetFolder: $(Build.ArtifactStagingDirectory)/SurveyJSLibraryBuild
      displayName: "copy version file to Build.ArtifactStagingDirectory"

    #publishLocation: 'Container' - store the artifact in Azure Pipelines
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: "$(Build.ArtifactStagingDirectory)/SurveyJSLibraryBuild/"
        ArtifactName: "SurveyJSLibraryBuild"
        publishLocation: "Container"
